const longText = """
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce in nunc vulputate justo dapibus semper eget eu enim. Vestibulum vel nibh nec tellus porta ornare id posuere mauris. Maecenas facilisis nunc eu urna efficitur sollicitudin. Maecenas varius massa vel vestibulum mollis. Proin fringilla placerat blandit. Sed ac ipsum in justo scelerisque imperdiet. Quisque rutrum purus eu suscipit pharetra. Donec a quam aliquet, tempor quam sed, fringilla felis. Donec dictum sapien quam, et fringilla enim ullamcorper non. Nam sit amet est lectus. Etiam vel malesuada tellus, eu tempor libero. Donec malesuada, ipsum vel ornare bibendum, arcu felis euismod ante, non maximus leo elit quis lectus. Fusce id tortor pulvinar, placerat dolor in, blandit ex.

Etiam quam justo, lobortis vel tincidunt sodales, lobortis sed nisl. Quisque dignissim, quam sit amet finibus malesuada, metus diam cursus dolor, sit amet lacinia risus augue ut dui. Pellentesque et risus sollicitudin, posuere orci eget, sagittis neque. Curabitur venenatis interdum dui at accumsan. Nunc non cursus ante. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Quisque sit amet accumsan libero, ut commodo sem. Proin metus lacus, porttitor sit amet ante sed, ultricies congue odio. Interdum et malesuada fames ac ante ipsum primis in faucibus. Fusce dictum eget nisl ac cursus. Fusce porta, enim id condimentum iaculis, sapien ex tristique ex, ac lobortis lorem nunc at magna. Donec ultricies hendrerit congue. Duis rutrum sodales urna sed tempor. Phasellus ipsum orci, aliquam malesuada sollicitudin ullamcorper, rutrum nec tortor.

Nam vel vehicula dui. Quisque consequat leo at eleifend pellentesque. Praesent ullamcorper, leo vitae hendrerit accumsan, arcu augue rhoncus nunc, a accumsan mi quam sit amet nibh. Nullam id nisl vehicula, pulvinar quam a, sodales libero. Suspendisse at iaculis lacus. Aliquam nec cursus felis, a pretium diam. Quisque id dolor scelerisque ligula placerat placerat. Phasellus ante dui, euismod id fermentum eu, rutrum eu erat.

Cras ullamcorper semper risus, auctor imperdiet eros iaculis id. Sed posuere non ipsum vel iaculis. Fusce viverra lorem eu ligula mattis, sit amet fringilla est blandit. Fusce volutpat elit erat, ut lacinia magna sollicitudin sed. Aenean blandit odio at varius rutrum. Morbi feugiat lacus nec ultrices convallis. Morbi vehicula leo est. Nulla viverra lorem ut semper consectetur.

Sed consectetur lacinia nunc, at pellentesque mi pretium at. Sed pharetra vestibulum molestie. Duis accumsan urna quis ligula sagittis consequat. Sed pulvinar ipsum eu diam aliquet, at finibus sapien vestibulum. Nam dictum nulla ipsum, a venenatis turpis finibus ac. Sed venenatis id sapien eget pulvinar. Ut condimentum non tellus at feugiat. Duis tincidunt aliquet urna, eget aliquet sapien fringilla at. Aliquam tincidunt nisl rutrum dolor maximus, nec imperdiet dolor rutrum.

Aenean quis ante eget justo finibus fermentum et ac ante. Praesent convallis leo in accumsan consequat. Duis semper augue egestas, interdum ligula in, lobortis ante. Praesent molestie nibh euismod enim interdum, sit amet efficitur elit tincidunt. Nunc sed tristique nibh, vel placerat velit. Nullam id vehicula arcu. Vivamus ex augue, faucibus consectetur viverra a, tincidunt nec sapien.

Nullam pellentesque dapibus turpis, at facilisis eros convallis et. Sed finibus, purus et dapibus ultricies, lorem augue euismod lorem, a laoreet augue turpis et enim. Suspendisse finibus nisl id sem fermentum, eget molestie ex efficitur. Nulla rutrum sed purus non fringilla. Vestibulum sed risus nibh. Proin a posuere arcu. Mauris pellentesque faucibus justo, vitae molestie enim. In vel nisl vehicula, rhoncus metus at, molestie nunc.

Maecenas eu massa posuere, venenatis mauris a, dictum enim. Nam quis facilisis lorem, vel tincidunt mi. Ut laoreet tincidunt turpis et sodales. Maecenas blandit eu elit sit amet vehicula. Nam non nulla malesuada, porta dolor et, gravida erat. Phasellus odio eros, sollicitudin id efficitur sed, finibus egestas orci. Suspendisse bibendum nisi eu quam pulvinar, vitae sagittis odio blandit. Ut nec ex aliquet, lobortis magna porttitor, aliquam ligula. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed a justo aliquam, ultricies ipsum eu, ullamcorper sem.

Proin accumsan neque id arcu posuere dignissim. Nulla imperdiet, nisl at pharetra faucibus, nulla quam consectetur elit, a gravida magna urna id enim. Morbi metus felis, tincidunt at imperdiet eu, pellentesque vel tellus. Nunc ac interdum mauris, ac dictum diam. Vivamus sit amet lacus enim. Aenean eu dictum eros. Etiam egestas lacus eget tellus commodo imperdiet.

Suspendisse sit amet eleifend eros. Mauris aliquet maximus tortor. Vivamus pharetra viverra ex, non convallis purus. Praesent varius vulputate justo in venenatis. Praesent in vestibulum libero. Praesent iaculis mauris nec diam interdum aliquam mattis ut leo. Quisque congue aliquam odio id sollicitudin. Donec scelerisque arcu a erat vehicula rhoncus. Phasellus commodo porta tortor aliquet consequat. Praesent sagittis, purus eu dignissim elementum, diam libero feugiat leo, in mattis turpis arcu id neque.

Quisque efficitur vitae arcu in volutpat. Nunc finibus justo facilisis diam tristique, sit amet tristique sem euismod. Ut blandit non diam sit amet molestie. Vestibulum ut enim ex. Sed consectetur, turpis sit amet condimentum venenatis, ex augue tincidunt tortor, eget lacinia nunc ligula id nisi. Etiam leo magna, gravida vel ultricies sit amet, tristique ac lorem. Donec nec dui eu ipsum consectetur ultricies aliquet in odio. Sed turpis tellus, convallis vel sapien nec, sollicitudin fermentum mi. Etiam at pretium nulla, quis euismod nisi. Aenean magna nisi, faucibus vitae elit at, sodales hendrerit metus. Cras purus augue, ornare quis nibh et, aliquet congue arcu. Etiam vel ex mi. In venenatis et tellus vel vestibulum.

Nullam dapibus vehicula lectus, ac sagittis diam facilisis nec. Fusce tellus augue, pellentesque nec dapibus ac, rhoncus ornare magna. Sed nunc odio, aliquet ac placerat in, blandit sed nisl. Quisque non ultrices purus. Praesent pretium sed magna imperdiet maximus. Vestibulum vitae quam nulla. In suscipit consectetur dolor, sit amet euismod purus sodales non. Suspendisse semper nisi at leo imperdiet, sit amet laoreet ligula rhoncus. Phasellus ut luctus eros, id tincidunt nunc. Sed et purus quis erat euismod placerat vitae at massa. Morbi quis blandit arcu.

Nullam interdum felis suscipit lectus maximus, in vulputate quam condimentum. Phasellus efficitur sollicitudin tellus, vel sagittis justo feugiat eget. Quisque maximus gravida eros, eget condimentum purus. Morbi porttitor quis risus quis pulvinar. Pellentesque nisl massa, rhoncus a fermentum in, sagittis tristique nisl. Praesent varius vitae diam ut interdum. Aenean viverra massa imperdiet gravida ornare. Cras sit amet velit laoreet, posuere ipsum ut, rhoncus est. Etiam at auctor est. Donec mollis accumsan enim id cursus. Aenean leo orci, accumsan sed blandit non, mattis vel risus.

Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Pellentesque ac luctus arcu, eu hendrerit diam. Vestibulum sagittis lacus id justo efficitur consequat. Nunc risus dolor, venenatis et sapien a, ullamcorper tempus lectus. In at ante ac arcu tincidunt interdum at at nulla. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Ut dapibus accumsan urna ut viverra. Quisque nec odio consectetur, laoreet felis nec, ultricies purus. Aenean tincidunt tristique dolor at rhoncus. Sed tincidunt, eros eu lacinia dapibus, lacus lacus molestie tellus, eu maximus libero urna non turpis. Cras eget nisi ante.

Vivamus tincidunt neque sit amet hendrerit vulputate. Integer volutpat accumsan sagittis. Etiam fringilla, diam id ultricies ornare, dolor lacus aliquam lacus, a facilisis nulla nisi a nunc. Donec vehicula vestibulum dui, a scelerisque erat consectetur eu. Quisque laoreet nisl ipsum, in mattis enim condimentum a. Maecenas magna est, dapibus vitae dictum in, blandit quis risus. Nam lorem eros, venenatis non ligula ut, efficitur finibus odio. Ut vel eros libero. Nullam nec condimentum eros, vitae posuere neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur maximus finibus sagittis. Donec sollicitudin, turpis vitae dictum dapibus, augue libero semper eros, non blandit velit dui a est. Vestibulum auctor urna quis lacinia varius. Integer laoreet, ex eget cursus rutrum, odio velit facilisis tortor, eu pharetra tortor lacus vel mi. Praesent eu suscipit dolor.

Quisque ut massa enim. Integer felis erat, volutpat nec lacus vitae, tempor condimentum dui. Pellentesque rutrum turpis nec nunc egestas, non euismod neque dignissim. Proin auctor elit eget ex faucibus varius. Cras vitae mi enim. Aliquam ante lectus, interdum quis nunc non, porttitor viverra enim. Proin eget porta dui, sed consequat arcu. Maecenas et est id enim ullamcorper gravida feugiat a odio. Fusce id justo blandit, auctor ipsum et, tempus enim. Cras ex velit, faucibus ut justo sit amet, iaculis semper lectus. Sed maximus sed sem id commodo. Donec viverra erat eu quam bibendum consectetur. Sed condimentum feugiat euismod. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Quisque pharetra consequat mauris vel gravida.

In id sodales metus. Suspendisse potenti. Ut ultricies, neque et convallis vehicula, velit sem ullamcorper purus, eu vehicula quam lorem eu arcu. Nam rutrum, sem vitae tempor rhoncus, metus ex semper enim, in ornare sem augue at magna. Morbi eu viverra eros. Curabitur aliquet purus purus, non viverra felis egestas ut. Aenean pellentesque lectus a nisl tincidunt, id imperdiet magna rutrum. Donec euismod elementum dapibus. Integer ac auctor justo. Curabitur luctus eros lacus, in tincidunt velit venenatis et.

Vivamus scelerisque viverra vulputate. Vivamus tincidunt eros ac nunc finibus, sit amet blandit libero semper. Sed euismod augue quis sapien luctus egestas. Sed vestibulum ornare ipsum, non faucibus erat ornare at. Curabitur pretium purus sem, non posuere ligula condimentum eget. Fusce congue nisi nisi, non vestibulum nisl condimentum vel. Nunc mollis libero vel aliquam imperdiet. Aliquam ut laoreet turpis.

Duis eros eros, tempor a mollis ut, ullamcorper in tellus. Etiam non dui eget urna laoreet porttitor vitae non leo. Suspendisse potenti. Praesent a neque accumsan, consectetur arcu convallis, facilisis risus. Pellentesque vel massa sed nulla pretium varius ut porttitor ligula. Sed rutrum est eget eros vulputate tempus. Donec vel luctus elit, id egestas urna. Morbi et magna scelerisque massa luctus feugiat. Curabitur porttitor odio sem, nec scelerisque ipsum lobortis non. Donec posuere dolor at ante dignissim interdum. Praesent feugiat enim et nisi facilisis dictum. Curabitur at pulvinar magna. Pellentesque ex augue, placerat sit amet commodo quis, iaculis vitae tellus.

Aliquam quis mi efficitur, aliquet dui quis, malesuada est. Vestibulum turpis diam, malesuada ut faucibus interdum, posuere eleifend turpis. Etiam enim ex, consequat ut facilisis et, ultrices luctus urna. Sed scelerisque interdum tellus, at ultrices tellus pulvinar ac. Cras placerat felis a erat lobortis, in tempor ex auctor. Sed eget porttitor nisl. Duis in purus nec dui suscipit fermentum in vitae lacus. Etiam sit amet pharetra elit. Morbi sit amet turpis eleifend, commodo nunc hendrerit, venenatis lectus.
""";
